{"timestamp": 1546482329472, "status": 503, "error": "Service Unavailable", "exception": "org.springframework.web.context.request.async.AsyncRequestTimeoutException", "message": "No message available", "path": "/api/plugins/telemetry/DEVICE/e99c82d0-d764-11e8-a085-4be867fcc47c/values/timeseries"}
Traceback (most recent call last):
  File "tc.py", line 195, in LogQuery
    for j, item in enumerate(subval):
TypeError: 'int' object is not iterable

